services:
  qwen-lite:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_NAME=distilgpt2  # Lightweight model for testing
      - RAG_DOCUMENT=/app/knowledge.md  # Path to RAG document
    volumes:
      - ./cache:/root/.cache/huggingface  # Cache models locally
    restart: unless-stopped